spring:
  cache-datasource:
    jdbc-url: jdbc:h2:mem:athena
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: PartiesPool
      auto-commit: false
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
  postgres-datasource:
    jdbc-url: jdbc:postgresql://192.168.1.100:5432/postgres   # dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 10
      maximum-pool-size: 100
      pool-name: AssetsPool
      auto-commit: false
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        use_sql_comments: false
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  main:
    allow-bean-definition-overriding: true