spring:
  datasource:
    jdbc-url: jdbc:h2:mem:athena
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: PartiesPool
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  main:
    allow-bean-definition-overriding: true